export const DIAGNOSTIC_CONFIG = {
  MAX_QUESTIONS: 3,
  CONSECUTIVE_CORRECT_TO_ADVANCE: 2,
  QUESTIONS_PER_TOPIC: 4,
  FOUNDATIONAL_TOPICS_LIMIT: 4,
} as const

export const SKIP_THRESHOLD = {
  MIN_ANSWERS: 3,
  MIN_CORRECT: 2,
} as const
